<a href="https://colab.research.google.com/github/Michael-1337/PDA_SOL/blob/main/hw_2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [ ]:
import numpy as np
np.__version__

'1.23.5'

2) Создать нулевой вектор размера 10

In [ ]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

3) Создать вектор заполненный 7-ами размера 7

In [ ]:
np.full(7, 7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
np.arange(10, 101, 2)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
np.random.randn(3, 3)[::-1]

array([[-1.32484951,  0.47748848,  0.72031063],
       [ 0.5415012 ,  0.93292924,  0.4683731 ],
       [ 1.56672809, -0.40222683,  2.0789356 ]])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
np.eye(4, k=1, dtype=int)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.**

In [ ]:
7 - np.identity(4, dtype=int) * 7 + np.diag([i for i in range(1, 5)])

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
arr = np.zeros((5, 5), dtype=int)
arr + np.arange(5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
arr = np.random.randn(10, 10)
arr - np.mean(arr, axis=1, keepdims=True)

array([[ 0.38778663, -1.03048909, -1.7740116 , -1.2989838 ,  0.19117345,
         2.52920888,  0.53188873, -0.14766302,  1.58866984, -0.97758002],
       [-0.03351569, -1.05552214, -0.09226601,  1.64313967,  1.16803409,
         1.21412088,  1.31288462, -1.05162228, -1.55814572, -1.5471074 ],
       [-1.84937554,  0.70675625,  3.03626636,  0.4703215 , -0.39623637,
        -0.06421483,  0.7747335 , -1.48847228, -2.42809866,  1.23832006],
       [ 0.29237928,  0.23489536,  0.38355158,  0.03071217, -0.94180273,
        -0.70383471,  1.12081965, -0.60194889, -0.16507872,  0.35030699],
       [ 0.01110887,  0.89120762, -0.27805787, -1.72185338, -0.77915099,
         1.10378715, -0.50797146, -0.1147892 ,  0.18571761,  1.21000167],
       [ 0.27082795,  0.41534233, -0.28551461, -0.4194248 , -0.51059306,
         1.27786217, -0.27458666, -0.13192063, -0.01851321, -0.32347947],
       [-0.58957523,  0.8416861 ,  0.70321308,  1.08982324,  0.71707787,
        -1.99952969,  0.53715339, -1.49463952

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
arr = np.random.randn(10, 10)
arr - np.median(arr, axis=0)

array([[ 0.82999016,  1.11550942, -0.16263394,  0.71358708, -0.0230741 ,
        -1.3342715 ,  2.53526124,  2.49412185, -0.02153904,  0.15733634],
       [-0.10597156, -0.21473585,  1.55340519,  1.01443294,  0.68537991,
         0.40370478,  0.78121996,  0.65709072,  0.02153904,  0.11574545],
       [ 0.10597156,  1.41685139,  0.16263394,  0.53843628, -3.40881644,
        -0.44230291, -0.7820049 ,  1.91491536,  1.75593711, -0.02065323],
       [-0.7164957 ,  0.64696171,  1.36591835,  1.08989001,  0.0230741 ,
        -0.54782145, -0.02939302, -2.06011164,  1.68613308, -0.57323085],
       [ 0.80878021, -0.41191188, -1.29804276, -0.57885904, -0.2883592 ,
         0.92835883, -1.09517117,  1.02645032, -0.05901061, -0.02905933],
       [-0.19266794, -0.06495047, -0.86685433,  0.25741061, -0.34144962,
        -0.10932879,  1.05352358, -0.1890046 , -0.87468985,  0.70542863],
       [ 0.49471367,  1.0888733 , -0.38435738, -0.83587836,  1.44916339,
         0.85593939,  0.02939302, -0.61075431

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
arr = np.random.randn(5, 5)
np.concatenate((arr, np.max(arr, axis=1, keepdims=True), np.min(arr, axis=1, keepdims=True)), axis=1)

array([[-0.22021234,  0.08278294,  0.05163401, -0.76628225, -0.62918321,
         0.08278294, -0.76628225],
       [ 0.98725299, -0.54980346, -0.21920924,  0.20953029, -0.00837095,
         0.98725299, -0.54980346],
       [ 0.81614486,  0.54262786,  2.8258056 , -1.10152001,  0.25418804,
         2.8258056 , -1.10152001],
       [ 1.38489403,  0.59264897, -2.54165157,  0.80160271, -0.77280473,
         1.38489403, -2.54165157],
       [ 0.31798273, -1.30363315,  1.35029015, -0.45934025, -0.01421905,
         1.35029015, -1.30363315]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [ ]:
arr = np.arange(1, 51)
odd = arr[::2].reshape(5, 5)
even = arr[1::2].reshape(5, 5)
np.linalg.inv(np.matmul(odd, even)) #det = 0

LinAlgError: ignored

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
arr = np.zeros((8,8), dtype=int)
arr[::2, ::2] = 1
arr[1::2, 1::2] = 1
arr

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])